security:
    encoders:
        AppBundle\Infrastructure\Core\User:
            algorithm: bcrypt
            cost: 12
    providers:
        main:
          entity:
            class: AppBundle\Infrastructure\Core\User
            property: username
    firewalls:

        api:
          pattern: ^/api
          security: false

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            anonymous: ~

        secured_area:
            pattern:    ^/
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /login

    role_hierarchy:
        ROLE_SYSTEM_ADMIN: ROLE_USER

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/system/account, roles: ROLE_USER }
        - { path: ^/system, roles: ROLE_SYSTEM_ADMIN }
        - { path: ^/, roles: ROLE_USER }

