services:

    # REPOSITORIES
    category_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ["AppBundle\\Infrastructure\\Product\\Category"]
