AppBundle\Infrastructure\Core\Seller:
    type: entity
    repositoryClass: AppBundle\Infrastructure\Core\SellerRepository
    table: seller
    uniqueConstraints:
        UNIQ_FB1AD3FCD824A5CF:
            columns:
                - key_name
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        keyName:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
            column: key_name
        accessToken:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: access_token
    lifecycleCallbacks: {  }
