AppBundle\Infrastructure\Order\Item:
    type: entity
    repositoryClass: AppBundle\Infrastructure\Order\ItemRepository
    table: sales_order_item
    indexes:
        IDX_5DD6A86534C4B0ED:
            columns:
                - fk_order
        IDX_5DD6A86523653981:
            columns:
                - fk_product
        IDX_5DD6A865963867C1:
            columns:
                - fk_sales_order_item_status_market
        IDX_5DD6A86568E31F6:
            columns:
                - fk_sales_order_item_status_seller
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        total:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: total_amount
        sellerId:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: seller_id
        additions:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
    manyToOne:
        product:
            targetEntity: AppBundle\Infrastructure\Product\Product
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_product:
                    referencedColumnName: id
            orphanRemoval: false
        order:
            targetEntity: Order
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_order:
                    referencedColumnName: id
            orphanRemoval: false
        stateSeller:
            targetEntity: ItemStatus
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_sales_order_item_status_seller:
                    referencedColumnName: id
            orphanRemoval: false
        stateMarket:
            targetEntity: ItemStatus
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_sales_order_item_status_market:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
