AppBundle\Infrastructure\Order\ItemStatus:
    type: entity
    table: sales_order_item_status
    uniqueConstraints:
        UNIQ_91202FD8D824A5CF:
            columns:
                - key_name
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        keyName:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: key_name
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
