AppBundle\Infrastructure\Product\ExternalProduct:
    type: entity
    repositoryClass: AppBundle\Infrastructure\Product\ExternalProductRepository
    table: external_product
    indexes:
        IDX_AE8DDEE4B02ED5B:
            columns:
                - fk_seller
        IDX_AE8DDEE23653981:
            columns:
                - fk_product
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        sku:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        json:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        status:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
    manyToOne:
        product:
            targetEntity: Product
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_product:
                    referencedColumnName: id
            orphanRemoval: false
        seller:
            targetEntity: AppBundle\Infrastructure\Core\Seller
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_seller:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
