AppBundle\Infrastructure\Product\LoadProductReport:
    type: entity
    table: load_product_report
    indexes:
        IDX_F4331A0949F6025E:
            columns:
                - fk_load_product
        IDX_F4331A094B02ED5B:
            columns:
                - fk_market
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        sku:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        message:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        loadProduct:
            targetEntity: LoadProduct
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_load_product:
                    referencedColumnName: id
            orphanRemoval: false
        market:
            targetEntity: AppBundle\Infrastructure\Core\Market
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_market:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
